.\" $Id$
.TH "SYNCE-REMOVE-PROGRAM" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
synce-remove-program \- removes a program from your device

.SH SYNOPSIS
\fBsynce-remove-program\fR \fINAME\fR

.SH "DESCRIPTION"

.PP
\fBsynce-remove-program\fR removes a program on a device connected through
SynCE.

.TP
\fINAME\fR 
The name of the program on the device

.SH "AUTHOR"
.PP
David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1)
