.\" $Id$
.TH "SYNCE-INSTALL-CAB" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
synce-install-cab \- install .cab file

.SH SYNOPSIS
\fBsynce-install-cab\fR \fIFILENAME\fR

.SH "DESCRIPTION"

.PP
\fBsynce-install-cab\fR installs a .cab file on a device connected through
SynCE.

.TP
\fIFILENAME\fR 
The .cab file that will be installed.

.SH "AUTHOR"
.PP
David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1)
