.\" $Id$
.TH "synce-matchmaker" "1" "September 2003" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
synce-matchmaker \- Configure/view a device's partnership status

.SH SYNOPSIS
\fBsynce-matchmaker\fR [-d \fILEVEL\fR] [status|create|replace \fIINDEX\fR]

.SH "DESCRIPTION"
.PP
\fBsynce-matchmaker\fR is used to control a (pre Windows Mobile 5) device's 
partnership status. It can show the current status, create a new partnership 
or update existing partnerships.

.SH "OPTIONS"
.TP
status
Show the partnership status for the device. (Default)
.TP
create
Create a partnership with the device.
.TP
replace \fIINDEX\fR
Replace a partnership on the device (\fIINDEX\fR is 1 or 2).
.TP
clear \fIINDEX\fR
Clear a partnership on the device (\fIINDEX\fR is 1 or 2).

.SH "AUTHOR"
.PP
This manual page was written by Jonathan McDowell <noodles@earth.li>
.SH "SEE ALSO"
synce(1)
