#!/bin/sh
rm -f config.cache
echo 'Please ignore "warning: AC_TRY_RUN called without default to allow cross compiling"'
set -x -e
aclocal -I m4
libtoolize --force
autoheader
automake --foreign --add-missing
autoconf
