#!/usr/bin/env python
#    Copyright (C) 2007 Guido Diepen
#    Email: Guido Diepen <guido@guidodiepen.nl>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
############################################################################## 

#from synce_kpm.synce_kpm_mainwindow import synce_kpm_mainwindow
#from PyQt4 import QtGui
import sys
import os

#sys.path.append('/home/guido/syncing/synce-kpm/data')
#ys.path.insert(0,'/home/guido/syncing/synce-kpm/data')

currentDir = os.path.abspath(os.path.dirname(__file__))
print os.path.join (currentDir, "data")
#print join(os.path.abspath(__file__), "data")


#app = QtGui.QApplication(sys.argv)
#mainWindow = synce_kpm_mainwindow()
#mainWindow.show()
#app.exec_()
