.\" $Id$
.TH "SYNCE-SERIAL-CONFIG" "8" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
synce-serial-config \- Configure a serial device for use with SynCE.

.SH SYNOPSIS
\fBsynce-serial-config\fR \fIserial-device\fR [\fIlocal_ip_address:remote_ip_address\fR]

.SH "DESCRIPTION"
.PP
\fBsynce-serial-config\fR is used to setup a connection using serial cable or
infrared. 
.PP
This configuration must be done with root privileges.

.SH "OPTIONS"
.TP
\fBserial-device\fR
The name of the serial device that is used for the serial connection.

.TP
\fBlocal_ip_address:remote_ip_address\fR
The IP adresses used for the serial connection. See pppd(8) for details about this configuration option.

.SH "AUTHOR"
.PP
This manual page was written by David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1) pppd(8) synce-serial-start(8) synce-serial-abort(8)
