.\" $Id$
.TH "SYNCE-SERIAL-ABORT" "8" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
synce-serial-abort \- Force a SynCE serial connection to abort.

.SH SYNOPSIS
\fBsynce-serial-abort\fR

.SH "DESCRIPTION"
.PP
\fBsynce-serial-abort\fR is used to start a connection using serial cable or
infrared. The connection must first be started with synce-serial-start(8).
.PP
This must be done with root privileges.

.SH "AUTHOR"
.PP
This manual page was written by David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1) pppd(8) synce-serial-config(8) synce-serial-start(8)
