.\" Copyright 2007 Mark Ellis (mark_ellis@users.sourceforge.net)
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy of
.\" this software and associated documentation files (the "Software"), to deal in
.\" the Software without restriction, including without limitation the rights to
.\" use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
.\" of the Software, and to permit persons to whom the Software is furnished to do
.\" so, subject to the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.TH SYNCE_INFO_NEW 3  2007-08-26 "The SynCE Project" "http://www.synce.org/"
.SH NAME
synce_info_new \- allocate a new SynceInfo struct
.SH SYNOPSIS
.nf
.B #include <synce.h>
.sp
.BI "SynceInfo *synce_info_new(const char *" device_name );
.sp
.BI "void synce_info_destroy(SynceInfo *" info );
.fi
.SH DESCRIPTION
The
.BR synce_info_new ()
function returns a pointer to a newly allocated and populated
SynceInfo struct for a mobile device.
.sp
If
.BR device_name
is non-NULL, the returned struct relates to a mobile device with that name, or NULL if no device of that name is connected.
.sp
If
.BR device_name
is NULL, the exact behaviour depends on the flavour of dccm daemon in use.
When using
.BR vdccm (1)
or the deprecated
.BR dccm (1),
the current active device is selected. This is usually the last device connected, specifically that described in the active_connection file which is by default
in the ~/.synce/ directory. With 
.BR odccm (1)
the first device connected will be returned.
.sp
This struct should be freed with
.BR synce_info_destroy (3).
.sp
.RS
.nf
typedef struct _SynceInfo {
    pid_t dccm_pid;      /* process id of dccm daemon */
    char* ip;            /* device ip address */
    char* password;      /* device password */
    int key;             /* device pass key */
    int os_version;      /* device OS version */
    int build_number;    /* OS build number */
    int processor_type;  /* device processor */
    int partner_id_1;    /* first sync partner id number */
    int partner_id_2;    /* second sync partner id number */
    char* name;          /* device name */
    char* os_name;       /* device OS name eg. PocketPC */
    char* model;         /* device hardware name */
    char* transport;     /* interface type */
    int fd;              /* file descriptor for RAPI calls */
} SynceInfo;
.fi
.RE
.PP
The particular fields populated depend on the flavour of dccm daemon in use.
.sp
The use of
.BR dccm (1)
is deprecated. When using
.BR vdccm (1)
all fields are populated except for 
.BR fd .
With 
.BR odccm (1)
only 
.BR name,
.BR os_version,
.BR transport
and 
.BR fd
are used.
.SH "RETURN VALUE"
The
.BR synce_info_new ()
function returns a pointer to the allocated SynceInfo struct,
or NULL if an error occured.
.SH "SEE ALSO"
.BR synce (7),
.BR odccm (1),
.BR vdccm (1)
