.\" $Id$
.TH "SynCE" "7" "November 2002" "The SynCE project" "http://www.synce.org/"
.SH NAME
SynCE \- A project for connecting to devices running Microsoft Windows Mobile.

.SH "DESCRIPTION"
The following steps are required to get started with SynCE with a WM5 or WM6 device:

.SS 
(1) Ensure kernel module is installed
.PP
You must either use the usb-rndis-[lite|ng] driver from SynCE, or if you are using a kernel >= 2.6.21 then you must have patched your kernel.

.SS
(2) Start the connection daemon (as root)
.PP
The odccm(1) program handles the SynCE connection. This daemon is run by the root.

.SS
(3) Run tools that access the device (as user)
.PP
See for example pls(1) and pcp(1).

.PP
See http://www.synce.org/ for more information about the SynCE project.
.SH "AUTHOR"
.PP
This manual page was written by David Eriksson <twogood@users.sourceforge.net>. It was later updated by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
odccm(1)

