#!/usr/bin/env python

import pywbxml

expected = "\x03\x01\x6a\x00\x00\x07\x56\x52\x03\x30\x00\x01\x01"

xml = r"""
<!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/"><FolderSync><SyncKey>0</SyncKey></FolderSync>
"""
print pywbxml.xml2wbxml(xml)
print expected

