#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import dbus

if len(sys.argv) != 3:
    print "Invalid argument count"
    sys.exit(1)

bus = dbus.SessionBus()
proxy_obj = bus.get_object("org.synce.SyncEngine", "/org/synce/SyncEngine")
engine = dbus.Interface(proxy_obj, "org.synce.SyncEngine")

name_to_id = {}
for id, name in engine.GetItemTypes().items():
    name_to_id[name.lower()] = id

items = []
for token in sys.argv[2].split(","):
    name = token.lower()
    items.append(name_to_id[name])

print "Creating partnership...",
sys.stdout.flush()
engine.CreatePartnership(sys.argv[1], items)
print "done"
