#!/usr/bin/env python
# -*- coding: utf-8 -*-

import gobject
import dbus
import dbus.glib
import sys

bus = dbus.SessionBus()
proxy_obj = bus.get_object("org.synce.SyncEngine", "/org/synce/SyncEngine")
engine = dbus.Interface(proxy_obj, "org.synce.SyncEngine")

if len(sys.argv) == 2:
    if sys.argv[1] == "clean":
        for pship in engine.GetPartnerships():
            id = pship[0]
            engine.DeletePartnership(id)
        sys.exit(0)
    elif sys.argv[1] == "create":
        SYNC_ITEM_CONTACTS = 1
        engine.CreatePartnership("Linux desktop", (SYNC_ITEM_CONTACTS,))
        sys.exit(0)
    else:
        print "Unknown command %s" % sys.argv[1]
        sys.exit(1)

def synchronized_cb():
    print "synchronized_cb"

    print "%d changes" % len(engine.GetRemoteChanges())

engine.StartSync()
engine.connect_to_signal("Synchronized", synchronized_cb)
print "%d changes" % len(engine.GetRemoteChanges())

mainloop = gobject.MainLoop()
mainloop.run()
