#!/bin/sh
rm -f config.cache
#echo 'Please ignore "warning: AC_TRY_RUN called without default to allow cross compiling"'
set -x -e
aclocal -I /usr/local/share/aclocal
autoheader
libtoolize --automake
automake --foreign --add-missing
autoconf

