#ifndef __synce_ids_h__
#define __synce_ids_h__

#define SYNCE_ID_BASE 0xd000
#define ID_IMADDRESS  (SYNCE_ID_BASE+0)
#define ID_NICKNAME  (SYNCE_ID_BASE+1)
#define ID_MESSAGING_ICQ (SYNCE_ID_BASE+2)
#define ID_MESSAGING_XMPP (SYNCE_ID_BASE+3)
#define ID_MESSAGING_MSN (SYNCE_ID_BASE+4)
#define ID_MESSAGING_GADU (SYNCE_ID_BASE+5)
#define ID_JOB_TITLE (SYNCE_ID_BASE+6)
#define ID_EMAIL4 (SYNCE_ID_BASE+7)
#define ID_EMAIL_EVOLUTION_META (SYNCE_ID_BASE+8)
#define ID_EMAIL2_EVOLUTION_META (SYNCE_ID_BASE+9)
#define ID_EMAIL3_EVOLUTION_META (SYNCE_ID_BASE+10)
#define ID_EMAIL4_EVOLUTION_META (SYNCE_ID_BASE+11)
#define ID_HOME_POST_OFFICE (SYNCE_ID_BASE+12)
#define ID_WORK_POST_OFFICE (SYNCE_ID_BASE+13)
#define ID_OTHER_POST_OFFICE (SYNCE_ID_BASE+14)
#define ID_X_MOZILLA_HTML (SYNCE_ID_BASE+15)
#define ID_X_EVOLUTION_BLOG_URL (SYNCE_ID_BASE+16)
#define ID_X_EVOLUTION_CALURI (SYNCE_ID_BASE+17)
#define ID_X_EVOLUTION_FBURL (SYNCE_ID_BASE+18)
#define ID_X_EVOLUTION_VIDEOURL (SYNCE_ID_BASE+19)
#define ID_X_EVOLUTION_MANAGER (SYNCE_ID_BASE+20)

#endif
