#ifndef __synce_ids_h__
#define __synce_ids_h__

#define SYNCE_ID_BASE 0xd000
#define ID_IMADDRESS  (SYNCE_ID_BASE+0)
#define ID_NICKNAME  (SYNCE_ID_BASE+1)
#define ID_MESSAGING_ICQ (SYNCE_ID_BASE+2)
#define ID_MESSAGING_XMPP (SYNCE_ID_BASE+3)
#define ID_MESSAGING_MSN (SYNCE_ID_BASE+4)
#define ID_MESSAGING_GADU (SYNCE_ID_BASE+5)
#define ID_JOB_TITLE (SYNCE_ID_BASE+6)
#define ID_EMAIL4 (SYNCE_ID_BASE+7)
#define ID_EMAIL_EVOLUTION_META (SYNCE_ID_BASE+8)
#define ID_EMAIL2_EVOLUTION_META (SYNCE_ID_BASE+9)
#define ID_EMAIL3_EVOLUTION_META (SYNCE_ID_BASE+10)
#define ID_EMAIL4_EVOLUTION_META (SYNCE_ID_BASE+11)

#endif
