.\" $Id$
.TH "SYNCE-SOUND" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
synce-sound \- play sounds on device connect/disconnect

.SH SYNOPSIS
\fBsynce-sound\fR install | uninstall | connect | disconnect

.SH "DESCRIPTION"

.PP
\fBsynce-sound\fR plays a sound when a device is connected or disconnected from dccm.

.PP
To play .wav files, synce-sound uses the play program supplied in the
sox package.

.PP
No sounds are supplied with this program. The first time you connect after
running synce-sound install it will copy the files Infbeg.wav and Infend.wav
from the Windows directory on the device to the files connect.wav and
disconnect.wav in the ~/.synce/sounds/ directory. You can overwrite these files
to customize what sounds are played.

.SH "OPTIONS"
.TP
install
Install the script ~/.synce/scripts/synce-sound-runner.sh that uses
dccm calls to play a sound on connect and disconnect.

.TP
uninstall
Remove synce-sound-runner.sh.

.TP
connect
Play connect sound. Used by synce-sound-runner.sh.

.TP
disconnect
Play disconnect sound. Used by synce-sound-runner.sh.

.SH "AUTHOR"
.PP
David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1) dccm(1)
