.TH "odccm" 1 "April 2007" "The SynCE project" "http://www.synce.org"
.SH NAME
odccm \- Daemon to keep connection to Windows Mobile device
.SH SYNOPSIS
.B odccm
[-f]
.SH DESCRIPTION
A legacy-free dccm-implementation for Windows Mobile 5 (and newer) devices. It responds to keep alives and provides other members of the SynCE suite of tools with details of the connected device.
.SH OPTIONS
.TP
.B \-l, \-\-log\-level
Set logging level from 0 (none) to 6 (debug), default is 3.
.TP
.B \-f, \-\-foreground
Runs as non-daemon, sets logging level to 6.
.TP
.B --device-ip
Specify device's IP address.
.TP
.B --local-ip
Specify local IP address.
.TP
.B --local-netmask
Specify local netmask.
.TP
.B --local-broadcast
Specify local broadcast address.
.SH "AUTHOR"
This manual page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
