.TH "odccm" 1 "April 2007" "The SynCE project" "http://synce.org"
.SH NAME
odccm \- Daemon to keep connection to Windows Mobile device
.SH SYNOPSIS
.B odccm
[-f]
.SH DESCRIPTION
A legacy-free dccm-implementation for Windows Mobile 5 (and newer) devices. It responds to keep alives and provides other members of the SynCE suite of tools with details of the connected device.
.SH OPTIONS
.TP
.B \-f
Runs as non-daemon.
.SH "AUTHOR"
This manual page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
