# This spec file was generated by Gideon
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: rapip
Version: 0.1
Release: alpha
Vendor: Volker Christian
Copyright: GNU
Summary: kio_slave for PDA
Group: Development/kio_slave
Packager: Volker Christian
BuildRoot: %{_tmppath}/%{name}-root
Source: rapip-0.1.tar.gz

%description
An kio_slave to communicate with a PDA via the synce-package. The protocol is called rapip:/




%prep
%setup
CFLAGS="$RPM_OPT_FLAGS" CXXFLAGS="$RPM_OPT_FLAGS" ./configure \
--target=i386

%build
%configure
make

%install
rm -rf %{buildroot}
%makeinstall

%clean
rm -rf %{buildroot}

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
%files
%defattr(-, root, root)
%doc AUTHORS COPYING ChangeLog NEWS README TODO
%{_bindir}/*
%{_libdir}/*.so.*
%{_datadir}/%{name}
%{_mandir}/man8/*
%changelog
* 2003-01-27  Volker Christian <voc@soft.uni-linz.ac.at> Initial Release

