# This spec file was generated by Gideon
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html
%define prefix   /usr
%define name     synce-rapip
%define rel      1

Summary: Rapip-Suit: KDE-Integration of SynCE. Kio-slave and Tray-Icon.
Name: %{name}
Version: 0.6
Release: %{rel}
Vendor: The SynCE Project
Copyright: MIT
Group: Applications/Productivity
Distribution: SynCE RPM packages
Packager: Volker Christian <voc@users.sourceforge.net>
BuildRoot: %{_tmppath}/synce-root
Source: %{name}-%{version}.tar.gz
URL: http://synce.sourceforge.net/
Requires: synce-rra

%description
Rapip is part of the SynCE project:

  http://synce.sourceforge.net/

This Package is a KDE-Integration of SynCE. It consists of a kio_slave
(rapip), a KDE System-Tray Application (raki) and an enhanced direct cable
connection manager (vdccm).

Rapip: Lets you transparently interact with your PockePC via konqueror.
Raki:  Is a Linux-Incarnation of Activsync. It claims to be better than 
       Activesync in future.

%prep
%setup
#./configure --with-agsync=/home/voc/usr/src/synce/agsync-0.2-pre

%build
%configure --with-agsync=/home/voc/usr/src/synce/agsync-0.2-pre
make

%install
%makeinstall

%files
%defattr(-,root,root)
%{prefix}/bin/raki
%{prefix}/bin/vdccm
%{prefix}/include/rakisyncfactory.h
%{prefix}/include/rakisyncplugin.h
%{prefix}/include/rapiwrapper.h
%{prefix}/include/rra.h
%{prefix}/include/syncevent.h
%{prefix}/lib/kde3/kio_rapip.*
%{prefix}/lib/librakikdeaddressbooksync.*
%{prefix}/share/applnk/Utilities/raki.desktop
%{prefix}/lib/librakiagsync.*
%{prefix}/share/services/rakiagsync.desktop
%{prefix}/share/apps/konqueror/servicemenus/cab_install.desktop
%{prefix}/share/apps/raki/Infbeg.wav
%{prefix}/share/apps/raki/Infend.wav
%{prefix}/share/apps/raki/scripts/dccm.sh
%{prefix}/share/apps/raki/scripts/vdccm.sh
%{prefix}/share/doc/HTML/en/raki/index.cache.bz2
%{prefix}/share/doc/HTML/en/raki/index.docbook
%{prefix}/share/icons/hicolor/16x16/apps/raki.png
%{prefix}/share/icons/hicolor/16x16/apps/raki_bw.png
%{prefix}/share/icons/hicolor/16x16/apps/rapip.png
%{prefix}/share/icons/hicolor/16x16/apps/rapip_bw.png
%{prefix}/share/icons/hicolor/22x22/apps/raki.png
%{prefix}/share/icons/hicolor/22x22/apps/raki_bw.png
%{prefix}/share/icons/hicolor/22x22/apps/rapip.png
%{prefix}/share/icons/hicolor/22x22/apps/rapip_bw.png
%{prefix}/share/icons/hicolor/32x32/apps/raki.png
%{prefix}/share/icons/hicolor/32x32/apps/raki_bw.png
%{prefix}/share/icons/hicolor/32x32/apps/rapip.png
%{prefix}/share/icons/hicolor/32x32/apps/rapip_bw.png
%{prefix}/share/icons/hicolor/48x48/apps/raki.png
%{prefix}/share/icons/hicolor/48x48/apps/raki_bw.png
%{prefix}/share/icons/hicolor/48x48/apps/rapip.png
%{prefix}/share/icons/hicolor/48x48/apps/rapip_bw.png
%{prefix}/share/icons/hicolor/64x64/apps/raki.png
%{prefix}/share/icons/hicolor/64x64/apps/raki_bw.png
%{prefix}/share/icons/hicolor/64x64/apps/rapip.png
%{prefix}/share/icons/hicolor/64x64/apps/rapip_bw.png
%{prefix}/share/mimelnk/application/x-raki.desktop
%{prefix}/share/services/rakikdeaddressbooksync.desktop
%{prefix}/share/services/rapip.protocol
%{prefix}/share/servicetypes/rakisynchronizer.desktop
