.\" $Id$
.TH "DCCM" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
dccm \- Handle SynCE connection.

.SH SYNOPSIS
\fBdccm\fR [-d \fILEVEL\fR] [-f] [-h] [-p \fIpassword\fR]

.SH "DESCRIPTION"
.PP
\fBdccm\fR handles the SynCE connection.
.PP
This daemon should be run by the same user as will run any tools that connect
to the device.

.SH "OPTIONS"
.TP
-d \fILEVEL\fR
Set debug log level:
.IP
0 - No logging (default)
.IP
1 - Errors only
.IP
2 - Errors and warnings
.IP
3 - Everything

.TP
-f
Run in foreground. If this paramter is not specified, dccm will fork into the background.

.TP
-h
Display help message.

.TP
-p \fIpassword\fR
Use the specified password when connecting to a password-protected device.

.SH "AUTHOR"
.PP
This manual page was written by David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1)
