/* Generated by Pyrex 0.9.4.1 on Fri Mar  2 17:28:15 2007 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "rtfcomp/rtfcomp.h"
#include "stdlib.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_EndUnpack(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], Py_ssize_t nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from pyrtfcomp */


/* Implementation of pyrtfcomp */


static PyObject *__pyx_n_RTFException;
static PyObject *__pyx_n_RTFCompress;
static PyObject *__pyx_n_RTFDecompress;
static PyObject *__pyx_n_RTFConvertToUTF8;
static PyObject *__pyx_n_RTFConvertFromUTF8;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_dump;

static PyObject *__pyx_n_errorcode;
static PyObject *__pyx_n_strdesc;

static PyObject *__pyx_f_9pyrtfcomp_12RTFException___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9pyrtfcomp_12RTFException___init__ = {"__init__", (PyCFunction)__pyx_f_9pyrtfcomp_12RTFException___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_9pyrtfcomp_12RTFException___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_ec = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","ec",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_ec)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_ec);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":32 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_errorcode, __pyx_v_ec) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":33 */
  __pyx_1 = PyInt_AsLong(__pyx_v_ec); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(((char (*))LZRTFGetStringErrorCode(__pyx_1))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_strdesc, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyrtfcomp.RTFException.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_ec);
  return __pyx_r;
}

static PyObject *__pyx_k2p;

static char (__pyx_k2[]) = "Failed to convert: %s";

static PyObject *__pyx_f_9pyrtfcomp_12RTFException_dump(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9pyrtfcomp_12RTFException_dump = {"dump", (PyCFunction)__pyx_f_9pyrtfcomp_12RTFException_dump, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_9pyrtfcomp_12RTFException_dump(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":36 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_strdesc); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_k2p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyrtfcomp.RTFException.dump");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_len;

static PyObject *__pyx_f_9pyrtfcomp_RTFCompress(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9pyrtfcomp_RTFCompress(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_src = 0;
  unsigned char (*__pyx_v_result);
  unsigned int __pyx_v_reslen;
  int __pyx_v_rc;
  PyObject *__pyx_v_rstr;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"src",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_src)) return 0;
  Py_INCREF(__pyx_v_src);
  __pyx_v_rstr = Py_None; Py_INCREF(Py_None);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":43 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_INCREF(__pyx_v_src);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_src);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_rc = LZRTFCompress((&__pyx_v_result),(&__pyx_v_reslen),((unsigned char (*))PyString_AsString(__pyx_v_src)),__pyx_4);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":45 */
  __pyx_4 = (__pyx_v_rc != 0);
  if (__pyx_4) {

    /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":46 */
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_RTFException); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(__pyx_v_rc); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":48 */
  __pyx_1 = PyString_FromStringAndSize(((char (*))__pyx_v_result),__pyx_v_reslen); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_v_rstr);
  __pyx_v_rstr = __pyx_1;
  __pyx_1 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":49 */
  free(__pyx_v_result);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":50 */
  Py_INCREF(__pyx_v_rstr);
  __pyx_r = __pyx_v_rstr;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pyrtfcomp.RTFCompress");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rstr);
  Py_DECREF(__pyx_v_src);
  return __pyx_r;
}

static PyObject *__pyx_f_9pyrtfcomp_RTFDecompress(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9pyrtfcomp_RTFDecompress(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_src = 0;
  unsigned char (*__pyx_v_result);
  unsigned int __pyx_v_reslen;
  int __pyx_v_rc;
  PyObject *__pyx_v_rstr;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  unsigned int __pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {"src",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_src)) return 0;
  Py_INCREF(__pyx_v_src);
  __pyx_v_rstr = Py_None; Py_INCREF(Py_None);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":57 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_INCREF(__pyx_v_src);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_src);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsUnsignedLongMask(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_rc = LZRTFDecompress((&__pyx_v_result),(&__pyx_v_reslen),((unsigned char (*))PyString_AsString(__pyx_v_src)),__pyx_4);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":59 */
  __pyx_5 = (__pyx_v_rc != 0);
  if (__pyx_5) {

    /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":60 */
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_RTFException); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(__pyx_v_rc); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":62 */
  __pyx_1 = PyString_FromStringAndSize(((char (*))__pyx_v_result),__pyx_v_reslen); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  Py_DECREF(__pyx_v_rstr);
  __pyx_v_rstr = __pyx_1;
  __pyx_1 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":63 */
  free(__pyx_v_result);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":64 */
  Py_INCREF(__pyx_v_rstr);
  __pyx_r = __pyx_v_rstr;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("pyrtfcomp.RTFDecompress");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rstr);
  Py_DECREF(__pyx_v_src);
  return __pyx_r;
}

static PyObject *__pyx_f_9pyrtfcomp_RTFConvertToUTF8(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9pyrtfcomp_RTFConvertToUTF8(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_src = 0;
  PyObject *__pyx_v_isCompressed = 0;
  RTFOPTS __pyx_v_opts;
  unsigned char (*__pyx_v_result);
  unsigned int __pyx_v_reslen;
  int __pyx_v_rc;
  PyObject *__pyx_v_rstr;
  PyObject *__pyx_r;
  unsigned int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"src","isCompressed",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_src, &__pyx_v_isCompressed)) return 0;
  Py_INCREF(__pyx_v_src);
  Py_INCREF(__pyx_v_isCompressed);
  __pyx_v_rstr = Py_None; Py_INCREF(Py_None);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":72 */
  __pyx_v_opts.lenOpts = (sizeof(RTFOPTS ));

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":73 */
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_v_isCompressed); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  __pyx_v_opts.isCompressed = __pyx_1;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":75 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_INCREF(__pyx_v_src);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_src);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_rc = LZRTFConvertRTFToUTF8((&__pyx_v_result),(&__pyx_v_reslen),((unsigned char (*))PyString_AsString(__pyx_v_src)),__pyx_1,(&__pyx_v_opts));

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":77 */
  __pyx_5 = (__pyx_v_rc != 0);
  if (__pyx_5) {

    /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":78 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_RTFException); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_rc); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":80 */
  __pyx_2 = PyString_FromStringAndSize(((char (*))__pyx_v_result),__pyx_v_reslen); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_v_rstr);
  __pyx_v_rstr = __pyx_2;
  __pyx_2 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":81 */
  free(__pyx_v_result);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":82 */
  Py_INCREF(__pyx_v_rstr);
  __pyx_r = __pyx_v_rstr;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyrtfcomp.RTFConvertToUTF8");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rstr);
  Py_DECREF(__pyx_v_src);
  Py_DECREF(__pyx_v_isCompressed);
  return __pyx_r;
}

static PyObject *__pyx_f_9pyrtfcomp_RTFConvertFromUTF8(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9pyrtfcomp_RTFConvertFromUTF8(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_src = 0;
  PyObject *__pyx_v_header = 0;
  PyObject *__pyx_v_isCompressed = 0;
  RTFOPTS __pyx_v_opts;
  unsigned char (*__pyx_v_result);
  unsigned int __pyx_v_reslen;
  int __pyx_v_rc;
  PyObject *__pyx_v_rstr;
  PyObject *__pyx_r;
  unsigned int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  unsigned int __pyx_5;
  int __pyx_6;
  static char *__pyx_argnames[] = {"src","header","isCompressed",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_src, &__pyx_v_header, &__pyx_v_isCompressed)) return 0;
  Py_INCREF(__pyx_v_src);
  Py_INCREF(__pyx_v_header);
  Py_INCREF(__pyx_v_isCompressed);
  __pyx_v_rstr = Py_None; Py_INCREF(Py_None);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":90 */
  __pyx_v_opts.lenOpts = (sizeof(RTFOPTS ));

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":91 */
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_v_isCompressed); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_v_opts.isCompressed = __pyx_1;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":93 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_INCREF(__pyx_v_src);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_src);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_INCREF(__pyx_v_header);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_header);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_AsUnsignedLongMask(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_rc = LZRTFConvertUTF8ToRTF((&__pyx_v_result),(&__pyx_v_reslen),((unsigned char (*))PyString_AsString(__pyx_v_src)),__pyx_1,((unsigned char (*))PyString_AsString(__pyx_v_header)),__pyx_5,(&__pyx_v_opts));

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":95 */
  __pyx_6 = (__pyx_v_rc != 0);
  if (__pyx_6) {

    /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":96 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_RTFException); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_rc); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":98 */
  __pyx_2 = PyString_FromStringAndSize(((char (*))__pyx_v_result),__pyx_v_reslen); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_DECREF(__pyx_v_rstr);
  __pyx_v_rstr = __pyx_2;
  __pyx_2 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":99 */
  free(__pyx_v_result);

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":100 */
  Py_INCREF(__pyx_v_rstr);
  __pyx_r = __pyx_v_rstr;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyrtfcomp.RTFConvertFromUTF8");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rstr);
  Py_DECREF(__pyx_v_src);
  Py_DECREF(__pyx_v_header);
  Py_DECREF(__pyx_v_isCompressed);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_RTFCompress, "RTFCompress"},
  {&__pyx_n_RTFConvertFromUTF8, "RTFConvertFromUTF8"},
  {&__pyx_n_RTFConvertToUTF8, "RTFConvertToUTF8"},
  {&__pyx_n_RTFDecompress, "RTFDecompress"},
  {&__pyx_n_RTFException, "RTFException"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_dump, "dump"},
  {&__pyx_n_errorcode, "errorcode"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_strdesc, "strdesc"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"RTFCompress", (PyCFunction)__pyx_f_9pyrtfcomp_RTFCompress, METH_VARARGS|METH_KEYWORDS, 0},
  {"RTFDecompress", (PyCFunction)__pyx_f_9pyrtfcomp_RTFDecompress, METH_VARARGS|METH_KEYWORDS, 0},
  {"RTFConvertToUTF8", (PyCFunction)__pyx_f_9pyrtfcomp_RTFConvertToUTF8, METH_VARARGS|METH_KEYWORDS, 0},
  {"RTFConvertFromUTF8", (PyCFunction)__pyx_f_9pyrtfcomp_RTFConvertFromUTF8, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initpyrtfcomp(void); /*proto*/
PyMODINIT_FUNC initpyrtfcomp(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("pyrtfcomp", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":30 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_RTFException, "pyrtfcomp"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":31 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_9pyrtfcomp_12RTFException___init__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":35 */
  __pyx_2 = PyCFunction_New(&__pyx_mdef_9pyrtfcomp_12RTFException_dump, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n_dump, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_RTFException, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/scratchpad/Development/Local/librtfcomp/librtfcomp-1.01/python/./pyrtfcomp.pyx":84 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyrtfcomp");
}

static char *__pyx_filenames[] = {
  "pyrtfcomp.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
