
=head1 NAME

RRA - Perl Wrapper Interface to the librra from the SynCE Project
(http://synce.sourceforge.net)

=head1 SYNOPSIS

  use RRA;

  my $rra=rra_new();
  die "rra_connect failed" unless rra_connect($rra);

=head1 DESCRIPTION

The RRA module provides access to the librra C library for synchronization
with a Pocket PC.

=head1 SUPPORTED FUNCTIONS

=over

  rra_new
  rra_free
  rra_connect
  rra_disconnect
  rra_get_time_zone_information
  rra_get_object_types
  rra_type_id_from_name
  rra_get_object_ids
  rra_get_deleted_object_ids
  rra_object_get
  rra_object_put
  rra_object_new
  rra_object_update
  rra_object_delete
  rra_partner_set_current
  rra_partner_get_current
  rra_partner_replace
  rra_partner_create
  rra_partner_set_id
  rra_partner_get_id
  rra_partner_set_name
  rra_partner_get_name
  rra_contact_to_vcard
  rra_contact_from_vcard
  rra_appointment_to_vevent
  rra_appointment_from_vevent
  rra_task_to_vtodo
  rra_task_from_vtodo

=back

=head1 SEE ALSO

L<rra(1)>

L<Rapi2(1)>
L<Rapi2::Simple(3)>
L<Rapi2::Defs(3)>

L<synce(1)>

=head1 AUTHOR

Andreas Pohl <osar@users.sourceforge.net>


=cut
