.\" $Id$
.TH "PRM" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
prm \- remove file

.SH SYNOPSIS
\fBprm\fR [-d \fILEVEL\fR] [-p \fIDEVPATH\fR] [-h] \fIFILE\fR

.SH "DESCRIPTION"

.PP
\fBprm\fR removes a file on a device connected through SynCE.

.PP
Forward slashes ('/') on the command line are converted to backward slashes ('\\').

.SH "OPTIONS"

.TP
-d \fILEVEL\fR
Set debug log level:
.IP
0 - No logging (default)
.IP
1 - Errors only
.IP
2 - Errors and warnings
.IP
3 - Everything

.TP
-p \fIDEVPATH\fR
Use the device at the given path, instead of the default.

.TP
-h
Display help message.

.TP
\fIFILE\fR
Full path name to the file that should be removed.

.SH "AUTHOR"
.PP
This manual page was written by David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1) pcp(1) pls(1) pmv(1) pmkdir(1) prmdir(1)
