.\" $Id$
.TH "PRUN" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
prun \- run program

.SH SYNOPSIS
\fBprun\fR [\-d \fILEVEL\fR] [\-p \fIDEVNAME\fR] [\-h] \fIPROGRAM\fR [\-\-] [\fIPARAMETERS\fR]

.SH "DESCRIPTION"

.PP
\fBprun\fR starts a program on a device connected through SynCE.

.SH "OPTIONS"
.TP
\-d \fILEVEL\fR
Set debug log level:
.IP
0 - No logging (default)
.IP
1 - Errors only
.IP
2 - Errors and warnings
.IP
3 - Everything

.TP
\-p \fIDEVNAME\fR
Use the device with the given name, instead of the default.

.TP
\-h
Display help message.

.TP
\fIPROGRAM\fR 
The program that will be started.

.TP
--
Needed if \fIPARAMETERS\fR begin with a dash ('-').

.TP
\fIPARAMETERS\fR

Command line parameters to the program. Note that if you need to pass more than
one parameter to the program, you will need to enclose the parameters in
quotes.

.SH "AUTHOR"
.PP
David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1) pstatus(1)
