#!/usr/bin/env python

from pyrapi2 import *
from partnerships import *

s = RAPISession(SYNCE_LOG_LEVEL_DEFAULT)

i = 1
for partnership in get_partnerships(s):
    if partnership != None:
        print "%d: %s" % (i, partnership)
    else:
        print "%d: [slot empty]" % i
    i += 1

