
=head1 NAME

Rapi2 - Perl Wrapper Interface to the librapi2 from the SynCE Project
(http://synce.sourceforge.net)

=head1 SYNOPSIS

  use Rapi2;

  Rapi2::CeRapiInit();

=head1 DESCRIPTION

The Rapi2 module provides access to the librapi2 C library to communicate
with Windows CE devices from Perl. It is not completely implemented yet
and still under construction. At this time you can use database and file
access functions. For the whole list of supported routines see
L<SUPPORTED FUNCTIONS>.

=head1 SUPPORTED FUNCTIONS

=over

=item B<Initialization>

  CeRapiInit

=item B<Logging>

  synce_log_set_level

=item B<Files>

  CeCloseHandle
  CeCreateFile
  CeReadFile
  CeWriteFile
  CeCopyFileA
  CeFindAllFiles
  CeGetLastError
  CeCopyFile
  CeCreateDirectory
  CeDeleteFile
  CeFindFirstFile
  CeFindNextFile
  CeFindClose
  CeGetFileAttributes
  CeGetSpecialFolderPath
  CeMoveFile
  CeRemoveDirectory
  CeSetFileAttributes

=item B<Databases>

  CeCloseHandle
  CeCreateDatabase
  CeDeleteDatabase
  CeFindAllDatabases
  CeFindFirstDatabase
  CeFindNextDatabase
  CeOidGetInfo
  CeOpenDatabase
  CeReadRecordProps
  CeSeekDatabase
  CeWriteRecordProps

=back

=head1 SEE ALSO

L<Rapi2::Simple>

L<synce(1)> 

=head1 AUTHOR

Andreas Pohl (osar@users.sourceforge.net)


=cut
