.TH "synce-trayicon" 1 "July 2007" "The SynCE project" "http://www.synce.org"
.SH NAME
gcemirror \- GTK remote PDA viewer for synCE
.SH SYNOPSIS
.B gcemirror
[-d level] device-name
.SH DESCRIPTION
\fBgcemirror\fP is a GTK application for synCE, for
viewing and controlling a connected Windows CE based device remotely.
.SH OPTIONS
.TP
.B \-d level
Set debug log level: 0 - No logging, 1 - Errors only (default), 2 - Errors and warnings, 3 - Everything.
.SH "SEE ALSO"
synce(1),
vdccm(1),
odccm(1)
.SH "AUTHOR"
This manual page was written by Mark Ellis <mark@mpellis.org.uk>.
