.\" $Id$
.TH "RRA" "1" "November 2002" "The SynCE project" "http://synce.sourceforge.net/"
.SH NAME
rra \- Synchronization application.

.SH SYNOPSIS
\fBrra\fR [-d \fILEVEL\fR]

.SH "DESCRIPTION"
.PP
\fBrra\fR is used to synchronize.
.PP
You must be running DCCM as the same user in order to use this application.

.SH "OPTIONS"
.TP
-d \fILEVEL\f
Set debug log level:
.IP
0 - No logging (default)
.IP
1 - Errors only
.IP
2 - Errors and warnings
.IP
3 - Everything

.SH "AUTHOR"
.PP
This manual page was written by David Eriksson <twogood@users.sourceforge.net>.
.SH "SEE ALSO"
synce(1)
