#!/usr/bin/env python
# -*- coding: utf-8 -*-

import dbus

bus = dbus.SessionBus()
proxy_obj = bus.get_object("org.synce.SyncEngine", "/org/synce/SyncEngine")
engine = dbus.Interface(proxy_obj, "org.synce.SyncEngine")

item_types = engine.GetItemTypes()
i = 0
for id, name, host, items in engine.GetPartnerships():
    print "ID: %#x" % id
    print "Name: '%s'" % name
    print "Host: '%s'" % host
    str = "["
    for id in items:
        str += " %s" % item_types[id]
    str += " ]"
    print "Items: %s" % str
    i += 1

if i == 0 or i > 1:
    suffix = "s"
else:
    suffix = ""

if i > 0:
    print
print "%d partnership%s" % (i, suffix)
